#!/bin/bash
# project_info.sh — LocalLLM Android Project Info Script
# Displays project structure and available Gradle tasks.

echo "=================================================="
echo "  LocalLLM — Android On-device LLM Chat App"
echo "=================================================="
echo ""
echo "This is a pure Android application."
echo "It requires Android SDK + a device/emulator to run."
echo ""
echo "--- Project Structure ---"
echo "app/          Android application module (Kotlin + Jetpack Compose)"
echo "mlc4j/        Native bridge to MLC LLM runtime (JNI)"
echo "download-core/ Model download/install logic (OkHttp)"
echo "docs/          Documentation"
echo "scripts/       Dev utility scripts"
echo ""
echo "--- Tech Stack ---"
echo "Language:   Kotlin 2.0.21"
echo "UI:         Jetpack Compose + Material3"
echo "DI:         Hilt 2.52"
echo "Database:   Room 2.6.1"
echo "Settings:   DataStore Preferences"
echo "Inference:  MLC LLM / TVM (via mlc4j native bridge)"
echo "Build:      Gradle 8.10.2 (Kotlin DSL)"
echo ""
echo "--- Common Gradle Commands ---"
echo "(Run these in your Android Studio or CI environment)"
echo ""
echo "  ./gradlew assembleDebug     Build debug APK"
echo "  ./gradlew assembleRelease   Build release APK"
echo "  ./gradlew test              Run unit tests"
echo "  ./gradlew lint              Run lint checks"
echo "  ./gradlew clean             Clean build outputs"
echo ""
echo "--- Modules ---"
echo "  :app          (Android Application)"
echo "  :mlc4j        (Android Library — native MLC bridge)"
echo "  :download-core (JVM Library — model downloader)"
echo ""
echo "--- Inference Engine ---"
echo "  FallbackInferenceEngine → tries MLCInferenceEngine first,"
echo "  falls back to FakeInferenceEngine if native libs unavailable."
echo ""
echo "NOTE: Full compilation requires Android SDK (not available in"
echo "      this Replit environment). Use Android Studio or a CI"
echo "      pipeline with Android SDK to build and deploy the APK."
echo ""
echo "=================================================="
